<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-PIPO6LO" failures="1" tests="2" name="runner.TestRunner" time="63.044" errors="0" timestamp="2025-08-22T12:12:59 IST" skipped="0">
  <testcase classname="runner.TestRunner" name="runScenario" time="35.843"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="27.201">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at stepdefinitions.PlaceOrderStepDef.the_user_clicks_on_add_to_cart_button(PlaceOrderStepDef.java:58)
at âœ½.the user clicks on Add to Cart button(file:///C:/Users/LENOVO/OneDrive/Desktop/CAPGEMINI%20%20training/BDD_SauceDemo/src/test/resources/features/placeorder.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.TestRunner -->
